### ISSUE TITLE
grok failure's OpenVPN and DHCP

### ISSUE THREAD

**Issue by lejonpart** [pfelk/pfelk#66] opened 2019-12-23 13:36 UTC
Hi

I found som parse errors that I hope you can help me straighten out. 

Will post the lines that fail, in this format,
event.original:
pf_message:
tags:

Lets start with OpenVPN

<28>Dec 23 13:19:27 openvpn[91034]: WARNING: 'cipher' is used inconsistently, local='cipher AES-256-GCM', remote='cipher AES-256-CBC'
WARNING: 'cipher' is used inconsistently, local='cipher AES-256-GCM', remote='cipher AES-256-CBC'
pf, openvpn, _grokparsefailure

<28>Dec 23 12:19:27 openvpn[91034]: WARNING: 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA1'
WARNING: 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA1'
pf, openvpn, _grokparsefailure

<28>Dec 23 11:19:27 openvpn[91034]: WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1550', remote='link-mtu 1558'
WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1550', remote='link-mtu 1558'
pf, openvpn, _grokparsefailure

Time for DHCP

<187>Dec 23 13:18:54 dhcpd: uid lease 192.168.54.71 for client b4:fb:e4:8d:41:92 is duplicate on 192.168.54.0/24
uid lease 192.168.54.71 for client b4:fb:e4:8d:41:92 is duplicate on 192.168.54.0/24
pf, dhcpd, _grokparsefailure

<191>Dec 23 13:14:24 dhcpd: reuse_lease: lease age 17401 (secs) under 25% threshold, reply with unaltered, existing lease for 192.168.54.54
reuse_lease: lease age 17401 (secs) under 25% threshold, reply with unaltered, existing lease for 192.168.54.54
pf, dhcpd, _grokparsefailure

<190>Dec 23 11:30:27 dhcpd: Wrote 46 leases to leases file.
Wrote 46 leases to leases file.	
pf, dhcpd, _grokparsefailure

<190>Dec 23 11:30:27 dhcpd: Wrote 0 new dynamic host decls to leases file.
Wrote 0 new dynamic host decls to leases file.
pf, dhcpd, _grokparsefailure

I'm running the patterns file named "pf-12.2019.grok"

Regards
Christian

**Comment by fktkrt** [comment] 2019-12-23 16:14
Could you paste here the relevant parts of your logstash log? You can find it here: `/var/log/logstash/logstash-plain.log`

**Comment by lejonpart** [comment] 2019-12-23 17:22
Sorry the entries does not get logged in that file (or at all), I turned on monitoring for the logstash pipeline but that will not help you. I don't know how to make all received entries end up in the logfile as well.

**Comment by fktkrt** [comment] 2019-12-23 17:40
Are you running logstash as a service? What service manager are you using? My guess is you have to configure your service manager, since logstash is forwarding entries to stdout while logging to `/var/log/logstash` by default.

**Comment by revere521** [comment] 2019-12-23 19:43
Some of these dhcpd and openvpn error/log entries may not fit the grok patterns well - i have been trying to write a pattern for unbound messages and i'm running into similar issues.  Since there are a slew of different log entry syntaxes, it may not be possible to capture them all.  They are errors and messages that mosty likely is not data that tabulates well into a visualization anyway (which would be one of the main point of parsing them to individual fields). 

I can say that if you change your settings for the openvpn, particularly picking the correct cypher suite the error entry may go away :)

They are just text string messages that maybe can be accounted for in a catch-all "greedydata" in the pattern?   In order to really get all of these, we will need a reference for every possible log message syntax

**Comment by revere521** [comment] 2019-12-23 19:59
IF you are up for a test, you can try changing the grok pattern in the pf-12.2019.grok to this:

```
# OPENVPN
#OPENVPN %{IP:[vpn_source][ip]}\:%{INT:[vpn_source][port]}%{SPACE}\[%{DATA:vpn_client}\]%{SPACE}Peer%{SPACE}Connection%{SPACE}Initiated%{SPACE}with%{GREEDYDATA}
OPENVPN (%{OPENVPNIP}|%{OPENVPNLOG})
OPENVPNIP %{IP:[vpn_source][ip]}\:%{INT:[vpn_source][port]}%{SPACE}\[%{DATA:vpn_client}\]%{SPACE}Peer%{SPACE}Connection%{SPACE}Initiated%{SPACE}with%{GREEDYDATA}
OPENVPNLOG (\[%{GREEDYDATA:openvpn_pid}]\s+)%{WORD:openvpn_log_level}: %{GREEDYDATA:openvpn_message}
```
It may get rid of the parse failures for the openvpn errors, as a catch all - and assuming the syntax does not change for the log entries.   


If i have some more time later, i'll try to figure out the syntax for the dchp "reuse_lease", "duplicate lease" and maybe general log messages from your examples.

**Comment by lejonpart** [comment] 2019-12-24 12:43
@fktkrt Yea its a ubuntu box and its running as a service.
@revere521 Thanks I just added your changes and will get back to you when the results are in.

**Comment by revere521** [comment] 2019-12-24 14:04
You may actually only need this, since the process name and pid are captured in a higer level pattern.  

```
OPENVPN (%{OPENVPNIP}|%{OPENVPNLOG})
OPENVPNIP %{IP:[vpn_source][ip]}\:%{INT:[vpn_source][port]}%{SPACE}\[%{DATA:vpn_client}\]%{SPACE}Peer%{SPACE}Connection%{SPACE}Initiated%{SPACE}with%{GREEDYDATA}
OPENVPNLOG %{GREEDYDATA:openvpn_message}
```

**Comment by lejonpart** [comment] 2019-12-24 16:40
@revere521 yea thats a catch all solution. I think "WARNING" msg should have its own so its easy to search for,

**Comment by revere521** [comment] 2019-12-24 17:20
the only problem is that not all the messages are prefixed with a statement behind a colon.  If it works you could split the difference with the pattern below, its really not necessary to parse the PID as in the first - that's already done regardless. 

```
 # OPENVPN
#OPENVPN %{IP:[vpn_source][ip]}\:%{INT:[vpn_source][port]}%{SPACE}\[%{DATA:vpn_client}\]%{SPACE}Peer%{SPACE}Connection%{SPACE}Initiated%{SPACE}with%{GREEDYDATA}
OPENVPN (%{OPENVPNIP}|%{OPENVPNLOG})
OPENVPNIP %{IP:[vpn_source][ip]}\:%{INT:[vpn_source][port]}%{SPACE}\[%{DATA:vpn_client}\]%{SPACE}Peer%{SPACE}Connection%{SPACE}Initiated%{SPACE}with%{GREEDYDATA}
OPENVPNLOG %{WORD:openvpn_log_level}: %{GREEDYDATA:openvpn_message}
```
Not sure if it will fail if the message doesn't have a "WORD:" to capture.  if they sometimes have hyphens or etc. i will have to be done with a regex based filter.... these can get complex real fast.   My preference will still be to keep it as simple as possible, you could still isolate the openvpn_message field and then search for warning or error in a discovery search either way

**Comment by fktkrt** [comment] 2019-12-24 17:49
In my experience if you have any special character in between words, the second part will be missed without a grokparsefailure, while using WORD. WORD is basically something like `\b\w+\b`

**Comment by revere521** [comment] 2019-12-24 17:58
you can include special characters if you know them in a regex - this adds words and hyphenated words: \b[\w\-]+\b)

**Comment by revere521** [comment] 2019-12-24 18:25
ultimately, since there is lots of disparate "log level"  or prefix messages - this is probably the best all-around solution for the openvpn part:
```
OPENVPNLOG (%{GREEDYDATA:openvpn_log_level}:)? %{GREEDYDATA:openvpn_message}
```

Similarly, i am testing a "catch-all" for the extra dhcpd messages to get rid of the occasional parse failures.  I'll let it run for a while - and if it solves more problems than it creates i'll commit them (if no one objects)

```
# DHCP (Optional)
DHCPD (%{DHCPDISCOVER}|%{DHCPOFFER}|%{DHCPREQUEST}|%{DHCPACK}|%{DHCPINFORM}|%{DHCPRELEASE}|%{DHCPGENERAL})
DHCPDISCOVER %{WORD:dhcp_action} from %{COMMONMAC:dhcp_client_mac}%{SPACE}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via (?<dhcp_client_vlan>[0-9a-z_]*)(: %{GREEDYDATA:dhcp_load_balance})?
DHCPOFFER %{WORD:dhcp_action} on %{IPV4:dhcp_client_ip} to %{COMMONMAC:dhcp_client_mac}%{SPACE}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via (?<dhcp_client_vlan>[0-9a-z_]*)
DHCPREQUEST %{WORD:dhcp_action} for %{IPV4:dhcp_client_ip}%{SPACE}(\(%{IPV4:dhcp_ip_unknown}\))? from %{COMMONMAC:dhcp_client_mac}%{SPACE}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via (?<dhcp_client_vlan>[0-9a-z_]*)(: %{GREEDYDATA:dhcp_$
DHCPACK %{WORD:dhcp_action} on %{IPV4:dhcp_client_ip} to %{COMMONMAC:dhcp_client_mac}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via (?<dhcp_client_vlan>[0-9a-z_]*)
DHCPINFORM %{WORD:dhcp_action} from %{IPV4:dhcp_client_ip} via %(?<dhcp_client_vlan>[0-9a-z_]*)
DHCPRELEASE %{WORD:dhcp_action} of %{IPV4:dhcp_client_ip} from %{COMMONMAC:dhcp_client_mac}%{SPACE}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via
DHCPGENERAL %{GREEDYDATA:dhcp_message}
```

In both cases it duplicates the "pf_message" field, while also fixing the parse failures, which is weird to me - but most assuredly means there is probably a better solution someplace.

**Comment by a3ilson** [comment] 2019-12-24 19:47
I utilized the Netgate Docs and some plagiarizing from the internet (https://github.com/elastic/logstash/blob/v1.4.2/patterns/grok-patterns) to build most of this setup.  The Netgate Docs were a great resource for firewall events (https://docs.netgate.com/pfsense/en/latest/monitoring/filter-log-format-for-pfsense-2-2.html).  However, I have not come across similar documentation pertaining to DHCP/OPENVPN (but haven't extensively looked).  

Those are good logs to address network issues and they are being properly tagged to filer out and/or hone in to isolate/address/correct.  I agree it would be great if they were parsed out nicely.  I am currently away but will check back and experiment with this endeavor next month (January).

**Comment by revere521** [comment] 2019-12-26 16:21
I agree that there is probably more that can be done to with the DHCP to parse additional strings more like the others that are there, I can look at it as well.   

For openvpn - the existing pattern appeared to be targeting clients connecting to pfsense as a vpn server  -  while the converse, pfsense as a vpn client, messages were failing.  These logs are probably best kept as messages in a single field.  They really only write the connection sequence at startup/reconnect - and occasionally errors.   The problem is that there isnt really a "classification" filed in every message, so if you try to target the very few that have a "WORD:", you end up grabbing or dropping the first word of the message in other that done have that syntax.  

here is an example dump from pfsense of the openvpn log messages:

```
Dec 26 11:06:37 	openvpn 	66132 	Initialization Sequence Completed
Dec 26 11:06:37 	openvpn 	66132 	/sbin/route add -net 10.10.10.10 10.10.10.10 255.255.255.255
Dec 26 11:06:37 	openvpn 	66132 	/usr/local/sbin/ovpn-linkup ovpnc1 1500 1550 10.10.10.10 10.10.10.10 init
Dec 26 11:06:37 	openvpn 	66132 	/sbin/ifconfig ovpnc1 10.10.10.10 10.10.10.10 mtu 1500 netmask 255.255.255.255 up
Dec 26 11:06:37 	openvpn 	66132 	do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Dec 26 11:06:37 	openvpn 	66132 	TUN/TAP device /dev/tun1 opened
Dec 26 11:06:37 	openvpn 	66132 	TUN/TAP device ovpnc1 exists previously, keep at program end
Dec 26 11:06:37 	openvpn 	66132 	ROUTE_GATEWAY 10.10.10.10/255.255.255.255 IFACE=pppoe0 HWADDR=00:00:00:00:00:00
Dec 26 11:06:37 	openvpn 	66132 	Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Dec 26 11:06:37 	openvpn 	66132 	Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Dec 26 11:06:37 	openvpn 	66132 	OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Dec 26 11:06:37 	openvpn 	66132 	OPTIONS IMPORT: route options modified
Dec 26 11:06:37 	openvpn 	66132 	OPTIONS IMPORT: --ifconfig/up options modified
Dec 26 11:06:37 	openvpn 	66132 	OPTIONS IMPORT: compression parms modified
Dec 26 11:06:37 	openvpn 	66132 	OPTIONS IMPORT: timers and/or timeouts modified
Dec 26 11:06:37 	openvpn 	66132 	PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 10.10.10.10,dhcp-option DNS 10.10.10.10,ping 10,comp-lzo no,route 10.10.10.10,topology net30,ifconfig 10.10.10.10 10.10.10.10,auth-token'
Dec 26 11:06:37 	openvpn 	66132 	SENT CONTROL [904abb249eb2e52a43c953dae42e9ec8]: 'PUSH_REQUEST' (status=1)
Dec 26 11:06:36 	openvpn 	66132 	[904abb249eb2e52a43c953dae42e9ec8] Peer Connection Initiated with [AF_INET]10.10.10.10:1000
Dec 26 11:06:36 	openvpn 	66132 	Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Dec 26 11:06:36 	openvpn 	66132 	WARNING: 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA1'
Dec 26 11:06:36 	openvpn 	66132 	WARNING: 'cipher' is used inconsistently, local='cipher AES-128-GCM', remote='cipher BF-CBC'
Dec 26 11:06:36 	openvpn 	66132 	WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1550', remote='link-mtu 1542'
Dec 26 11:06:36 	openvpn 	66132 	VERIFY OK: depth=1, C=US, ST=CA, L=LosAngeles, O=REMOVED, OU=REMOVED, CN=REMOVED, name=REMOVED, emailAddress=REMOVED
Dec 26 11:06:36 	openvpn 	66132 	VERIFY EKU OK
Dec 26 11:06:36 	openvpn 	66132 	++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Dec 26 11:06:36 	openvpn 	66132 	Validating certificate extended key usage
Dec 26 11:06:36 	openvpn 	66132 	VERIFY KU OK
Dec 26 11:06:36 	openvpn 	66132 	VERIFY OK: depth=1, C=US, ST=CA, L=LosAngeles, O=REMOVED, OU=REMOVED, CN=REMOVED, name=REMOVED, emailAddress=REMOVED
Dec 26 11:06:36 	openvpn 	66132 	WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Dec 26 11:06:36 	openvpn 	66132 	TLS: Initial packet from [AF_INET]10.10.10.10:1000, sid=51a81cba 3d85c57c
Dec 26 11:06:36 	openvpn 	66132 	UDPv4 link remote: [AF_INET]10.10.10.10:1100
Dec 26 11:06:36 	openvpn 	66132 	UDPv4 link local (bound): [AF_INET]10.10.10.10:0
Dec 26 11:06:36 	openvpn 	66132 	Socket Buffers: R=[42080->42080] S=[57344->57344]
Dec 26 11:06:36 	openvpn 	66132 	TCP/UDP: Preserving recently used remote address: [AF_INET]10.10.10.10:100
Dec 26 11:06:36 	openvpn 	66132 	NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Dec 26 11:06:36 	openvpn 	66132 	MANAGEMENT: unix domain socket listening on /var/etc/openvpn/client1.sock
Dec 26 11:06:36 	openvpn 	65896 	library versions: OpenSSL 1.0.2o-freebsd 27 Mar 2018, LZO 2.10
Dec 26 11:06:36 	openvpn 	65896 	OpenVPN 2.4.6 amd64-portbld-freebsd11.2 [SSL (OpenSSL)] [LZO] [LZ4] [MH/RECVDA] [AEAD] built on Oct 3 2018
Dec 26 11:06:36 	openvpn 	65896 	WARNING: file '/var/etc/openvpn/client1.up' is group or others accessible
Dec 26 11:06:35 	openvpn 	83501 	SIGTERM[hard,] received, process exiting
Dec 26 11:06:35 	openvpn 	83501 	/usr/local/sbin/ovpn-linkdown ovpnc1 1500 1550 10.10.10.10 10.10.10.10 init
Dec 26 11:06:35 	openvpn 	83501 	Closing TUN/TAP interface
```

**Comment by revere521** [comment] 2020-01-08 13:14
Ive been collecting dhcpd log data and it looks like there are only 2 types of messages that are not accounted for in the existing pattern. 

This type of message noting a duplicate lease: 


`1/7/2020 6:31  dhcpd     uid lease 192.168.1.210 for client 00:00:00:00:00:00 is duplicate   on 192.168.1.0/24
`

And blocks of messages that are more 'info' - usually at a process restart like this: 


```
1/3/2020   6:16 | dhcpd |   | All rights reserved.
1/3/2020   6:16 | dhcpd |   | All rights reserved.
1/3/2020   6:16 | dhcpd |   | Config file: /etc/dhcpd.conf
1/3/2020   6:16 | dhcpd |   | Copyright 2004-2018 Internet Systems   Consortium.
1/3/2020   6:16 | dhcpd |   | Copyright 2004-2018 Internet Systems   Consortium.
1/3/2020   6:16 | dhcpd |   | Database file: /var/db/dhcpd.leases
1/3/2020   6:16 | dhcpd |   | For info, please visit   https://www.isc.org/software/dhcp/
1/3/2020   6:16 | dhcpd |   | For info, please visit   https://www.isc.org/software/dhcp/
1/3/2020   6:16 | dhcpd |   | Internet Systems Consortium DHCP   Server 4.3.6-P1
1/3/2020   6:16 | dhcpd |   | Internet Systems Consortium DHCP   Server 4.3.6-P1
1/3/2020   6:16 | dhcpd |   | Listening on   BPF/re0/00:00:00:00:00:00/192.168.1.0/24
1/3/2020   6:16 | dhcpd |   | PID file: /var/run/dhcpd.pid
1/3/2020   6:16 | dhcpleases |   | Sending HUP signal to dns   daemon(26525)
1/3/2020   6:16 | dhcpleases |   | Sending HUP signal to dns   daemon(26525)
1/3/2020   6:16 | dhcpd |   | Sending on   BPF/re0/00:00:00:00:00:00/192.168.1.0/24
1/3/2020   6:16 | dhcpd |   | Sending on   Socket/fallback/fallback-net
1/3/2020   6:16 | dhcpd |   | Server starting service.
1/3/2020   6:16 | dhcpd |   | Wrote 0 deleted host decls to leases   file.
1/3/2020   6:16 | dhcpd |   | Wrote 0 new dynamic host decls to   leases file.
1/3/2020   6:16 | dhcpd |   | Wrote 5 leases to leases file.
1/3/2020   6:16 | dhcpleases |   | /etc/hosts changed size from original!
1/3/2020   6:16 | dhcpleases |   | Could not deliver signal HUP to   process because its pidfile (/var/run/unbound.pid) does not exist, No such   process.
1/3/2020   6:16 | dhcpleases |   | kqueue error: unknown
1/3/2020   6:16 | dhcpleases |   | Sending HUP signal to dns   daemon(13645)
1/3/2020   6:16 | dhcpleases |   | Sending HUP signal to dns   daemon(26525)
1/3/2020   6:16 | dhcpleases |   | /etc/hosts changed size from original!
1/3/2020   6:16 | dhcpleases |   | Sending HUP signal to dns   daemon(13645)
1/3/2020   6:16 | dhcpd |   | All rights reserved.
1/3/2020   6:16 | dhcpd |   | All rights reserved.
1/3/2020   6:16 | dhcpd |   | Config file: /etc/dhcpd.conf
1/3/2020   6:16 | dhcpd |   | Copyright 2004-2018 Internet Systems   Consortium.
1/3/2020   6:16 | dhcpd |   | Copyright 2004-2018 Internet Systems   Consortium.
1/3/2020   6:16 | dhcpd |   | Database file: /var/db/dhcpd.leases
1/3/2020   6:16 | dhcpd |   | For info, please visit   https://www.isc.org/software/dhcp/
1/3/2020   6:16 | dhcpd |   | For info, please visit   https://www.isc.org/software/dhcp/
1/3/2020   6:16 | dhcpd |   | Internet Systems Consortium DHCP   Server 4.3.6-P1
1/3/2020   6:16 | dhcpd |   | Internet Systems Consortium DHCP   Server 4.3.6-P1
1/3/2020   6:16 | dhcpd |   | Listening on   BPF/re0/00:00:00:00:00:00/192.168.1.0/24
1/3/2020   6:16 | dhcpd |   | PID file: /var/run/dhcpd.pid
1/3/2020   6:16 | dhcpleases |   | Sending HUP signal to dns   daemon(13645)
1/3/2020   6:16 | dhcpleases |   | Sending HUP signal to dns   daemon(13645)
1/3/2020   6:16 | dhcpd |   | Sending on   BPF/re0/00:00:00:00:00:00/192.168.1.0/24
1/3/2020   6:16 | dhcpd |   | Sending on   Socket/fallback/fallback-net
1/3/2020   6:16 | dhcpd |   | Server starting service.
1/3/2020   6:16 | dhcpd |   | Wrote 0 deleted host decls to leases   file.
1/3/2020   6:16 | dhcpd |   | Wrote 0 new dynamic host decls to   leases file.
1/3/2020   6:16 | dhcpd |   | Wrote 5 leases to leases file.
1/3/2020   6:16 | dhcpleases |   | kqueue error: unknown
1/3/2020   6:16 | dhcpleases |   | Sending HUP signal to dns   daemon(13645)
1/3/2020   6:16 | dhcpd |   | All rights reserved.
1/3/2020   6:16 | dhcpd |   | All rights reserved.
1/3/2020   6:16 | dhcpd |   | Config file: /etc/dhcpd.conf
1/3/2020   6:16 | dhcpd |   | Copyright 2004-2018 Internet Systems   Consortium.
1/3/2020   6:16 | dhcpd |   | Copyright 2004-2018 Internet Systems   Consortium.
1/3/2020   6:16 | dhcpd |   | Database file: /var/db/dhcpd.leases
1/3/2020   6:16 | dhcpd |   | For info, please visit   https://www.isc.org/software/dhcp/
1/3/2020   6:16 | dhcpd |   | For info, please visit   https://www.isc.org/software/dhcp/
1/3/2020   6:16 | dhcpd |   | Internet Systems Consortium DHCP   Server 4.3.6-P1
1/3/2020   6:16 | dhcpd |   | Internet Systems Consortium DHCP   Server 4.3.6-P1
1/3/2020   6:16 | dhcpd |   | Listening on   BPF/re0/00:00:00:00:00:00/192.168.1.0/24
1/3/2020   6:16 | dhcpd |   | PID file: /var/run/dhcpd.pid
1/3/2020   6:16 | dhcpleases |   | Sending HUP signal to dns   daemon(13645)
1/3/2020   6:16 | dhcpleases |   | Sending HUP signal to dns   daemon(13645)
1/3/2020   6:16 | dhcpd |   | Sending on   BPF/re0/00:00:00:00:00:00/192.168.1.0/24
1/3/2020   6:16 | dhcpd |   | Sending on   Socket/fallback/fallback-net
1/3/2020   6:16 | dhcpd |   | Server starting service.
1/3/2020   6:16 | dhcpd |   | Wrote 0 deleted host decls to leases   file.
1/3/2020   6:16 | dhcpd |   | Wrote 0 new dynamic host decls to   leases file.
1/3/2020   6:16 | dhcpd |   | Wrote 5 leases to leases file.
1/3/2020   6:16 | dhcpleases |   | kqueue error: unknown
1/3/2020   6:16 | dhcpleases |   | Sending HUP signal to dns   daemon(13645)
1/3/2020   6:16 | dhcpleases |   | /etc/hosts changed size from original!
1/3/2020   6:16 | dhcpleases |   | Could not deliver signal HUP to   process because its pidfile (/var/run/unbound.pid) does not exist, No such   process.
1/3/2020   6:16 | dhcpleases |   | Sending HUP signal to dns   daemon(32749)
1/3/2020   6:15 | dhcpleases |   | /etc/hosts changed size from original!
1/3/2020   6:15 | dhcpleases |   | Could not deliver signal HUP to   process because its pidfile (/var/run/unbound.pid) does not exist, No such   process.
1/3/2020   6:15 | dhcpleases |   | Sending HUP signal to dns   daemon(32749)
1/3/2020   6:15 | dhcpleases |   | /etc/hosts changed size from original!
1/3/2020   6:15 | dhcpleases |   | Sending HUP signal to dns   daemon(32749)

```

For the First one we could try to capture a dhcpduplicate message in the pattern, for the rest I think the DHCPGENERAL log message capture is sufficient.  

Thoughts?

**Comment by revere521** [comment] 2020-01-08 16:28
I am trying this right now for DHCP and OPENVPN.  IF no errors occur over the next day or so i'll report back:
```

# DHCP (Optional)
DHCPD (%{DHCPDISCOVER}|%{DHCPOFFER}|%{DHCPREQUEST}|%{DHCPACK}|%{DHCPINFORM}|%{DHCPRELEASE}|%{DHCPDUPLICATE}|%{DHCPGENERAL})
DHCPDISCOVER %{WORD:dhcp_action} from %{COMMONMAC:dhcp_client_mac}%{SPACE}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via (?<dhcp_client_vlan>[0-9a-z_]*)(: %{GREEDYDATA:dhcp_load_balance})?
DHCPOFFER %{WORD:dhcp_action} on %{IPV4:dhcp_client_ip} to %{COMMONMAC:dhcp_client_mac}%{SPACE}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via (?<dhcp_client_vlan>[0-9a-z_]*)
DHCPREQUEST %{WORD:dhcp_action} for %{IPV4:dhcp_client_ip}%{SPACE}(\(%{IPV4:dhcp_ip_unknown}\))? from %{COMMONMAC:dhcp_client_mac}%{SPACE}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via (?<dhcp_client_vlan>[0-9a-z_]*)(: %{GREEDYDATA:dhcp_$
DHCPACK %{WORD:dhcp_action} on %{IPV4:dhcp_client_ip} to %{COMMONMAC:dhcp_client_mac}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via (?<dhcp_client_vlan>[0-9a-z_]*)
DHCPINFORM %{WORD:dhcp_action} from %{IPV4:dhcp_client_ip} via %(?<dhcp_client_vlan>[0-9a-z_]*)
DHCPRELEASE %{WORD:dhcp_action} of %{IPV4:dhcp_client_ip} from %{COMMONMAC:dhcp_client_mac}%{SPACE}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via
DHCPDUPLICATE %{GREEDYDATA:dhcp_message} %{IPV4:dhcp_client_ip} for client %{COMMONMAC:dhcp_client_mac} is %{GREEDYDATA:dhcp_warning} on (?<dhcp_client_vlan>[0-9a-z_]*)
DHCPGENERAL %{GREEDYDATA:dhcp_message}

```

```
# OPENVPN
OPENVPN (%{OPENVPNIP}|%{OPENVPNLOG})
OPENVPNIP %{IP:[vpn_source][ip]}\:%{INT:[vpn_source][port]}%{SPACE}\[%{DATA:vpn_client}\]%{SPACE}Peer%{SPACE}Connection%{SPACE}Initiated%{SPACE}with%{GREEDYDATA}
OPENVPNLOG %{GREEDYDATA:openvpn_message}
```

**Comment by revere521** [comment] 2020-01-11 15:37
i've tried several iterations to capture that uid lease line - and it just wont happen. 

I'm good with committing the extra greedy data lines for each - and if we have a brainstorm later we can get more specific.

**Comment by revere521** [comment] 2020-01-12 16:18
i committed the following as catch-alls - its been a while running them in general and there are no parse failures.   We can revisit later if something better becomes apparent. 

 DHCPD:
```
# DHCP (Optional)
DHCPD (%{DHCPDISCOVER}|%{DHCPOFFER}|%{DHCPREQUEST}|%{DHCPACK}|%{DHCPINFORM}|%{DHCPRELEASE}|%{DHCPGENERAL})
DHCPDISCOVER %{WORD:dhcp_action} from %{COMMONMAC:dhcp_client_mac}%{SPACE}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via (?<dhcp_client_vlan>[0-9a-z_]*)(: %{GREEDYDATA:dhcp_load_balance})?
DHCPOFFER %{WORD:dhcp_action} on %{IPV4:dhcp_client_ip} to %{COMMONMAC:dhcp_client_mac}%{SPACE}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via (?<dhcp_client_vlan>[0-9a-z_]*)
DHCPREQUEST %{WORD:dhcp_action} for %{IPV4:dhcp_client_ip}%{SPACE}(\(%{IPV4:dhcp_ip_unknown}\))? from %{COMMONMAC:dhcp_client_mac}%{SPACE}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via (?<dhcp_client_vlan>[0-9a-z_]*)(: %{GREEDYDATA:dhcp_$
DHCPACK %{WORD:dhcp_action} on %{IPV4:dhcp_client_ip} to %{COMMONMAC:dhcp_client_mac}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via (?<dhcp_client_vlan>[0-9a-z_]*)
DHCPINFORM %{WORD:dhcp_action} from %{IPV4:dhcp_client_ip} via %(?<dhcp_client_vlan>[0-9a-z_]*)
DHCPRELEASE %{WORD:dhcp_action} of %{IPV4:dhcp_client_ip} from %{COMMONMAC:dhcp_client_mac}%{SPACE}(\(%{GREEDYDATA:dhcp_client_hostname}\))? via
DHCPGENERAL %{GREEDYDATA:dhcp_message}
```

OPENVPN: 
```
OPENVPN (%{OPENVPNIP}|%{OPENVPNLOG})
OPENVPNIP %{IP:[vpn_source][ip]}\:%{INT:[vpn_source][port]}%{SPACE}\[%{DATA:vpn_client}\]%{SPACE}Peer%{SPACE}Connection%{SPACE}Initiated%{SPACE}with%{GREEDYDATA}
OPENVPNLOG %{GREEDYDATA:openvpn_message}
```

**Closed as completed by revere521** 2020-01-12 16:18 UTC
