### ISSUE TITLE
Shards failing for suricata dashboard

### ISSUE THREAD

**Issue by brujoand** [pfelk/pfelk#206] opened 2020-11-08 08:31 UTC
**Describe the bug**
When launching the suricata dashboard I get several warnings about shards failing

shard | index | node | reason
-- | -- | -- | --
0 | pfelk-suricata-2020.11.06 | ay7U0CbuQ-qw5w4VZxICZg | illegal_argument_exception

illegal_argument_exception at shard 0index pfelk-suricata-2020.11.06node ay7U0CbuQ-qw5w4VZxICZg

Type: illegal_argument_exception
Reason: Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [suricata.eve.in_iface] in order to load field data by uninverting the inverted index. Note that this can use significant memory.

**To Reproduce**
Rigth so this one is a bit tricky. I'm using the helm charts for logstash, elasticsearch and kibana on version 7.9.3 from repo https://helm.elastic.co. Basically I've added the pipelines, grok pattern and csvs as ConfigMaps and I'm manually importing the dashboards and templates from the pfekl repo. This problem only occurs on the suricata dashboard, but my ELK knowledge is not good enough for me to figure out if this is a problem with the suricata templates or something I've done wrong. But the suricata, unbound and firewall dashboards all produce output.

**Screenshots**

**Firewall System (please complete the following information):**
 - OPNsense
 - OPNsense 20.7.4-amd64 
 
**Operating System (please complete the following information):**
 - FreeBSD 12.1-RELEASE-p10-HBSD
 
 **Installation method (manual, ansible-playbook, docker, script):** Helm chart
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - 7.9.3
 
 **Elasticsearch, Logstash, Kibana logs:**
This output from elastic search is the only interesting stuff I've found:
```
{"type": "deprecation", "timestamp": "2020-11-06T21:09:59,169Z", "level": "WARN", "component": "o.e.d.r.a.a.i.RestPutIndexTemplateAction", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-0", "message": "[types removal] Specifying include_type_name in put index template requests is deprecated. The parameter will be removed in the next major version.", "cluster.uuid": "5Wz7LRRwThe8CxIskBbulQ", "node.id": "M2n8Zv43QQC5-ijc07mUng"  }
{"type": "deprecation", "timestamp": "2020-11-07T08:00:01,512Z", "level": "WARN", "component": "o.e.d.a.b.BulkRequestParser", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-0", "message": "[types removal] Specifying types in bulk requests is deprecated.", "cluster.uuid": "5Wz7LRRwThe8CxIskBbulQ", "node.id": "M2n8Zv43QQC5-ijc07mUng"  }
```

**Comment by a3ilson** [comment] 2020-11-08 14:02
Greetings @brujoand 

I'll peel this back and revise the suricata template alleviating the error.

I'm also in the process of configuring pfelk via Helm Charts and wondering if you'd be interested in providing, sharing and/or authoring via [https://github.com/3ilson/kubernetes-pfelk](https://github.com/3ilson/kubernetes-pfelk)

**Comment by brujoand** [comment] 2020-11-08 14:17
Sure thing, I can make a PR with what I've got 👍

**Comment by a3ilson** [comment] 2020-11-08 14:20
@brujoand 

I just went through the suricata template and there were no text fields defined.  How do you have OPNsense configured?

![Capture](https://user-images.githubusercontent.com/16884679/98467324-aca75c80-21a2-11eb-9423-3f8a23f7f26e.PNG)

I would also be interested in the suricata fields you've parsed, specifically those index as text fields.  Below is an example list of fields 

```
@timestamp
@version
_id
_index
_score
_type
destination.as.ip
destination.as.number
destination.as.organization.name
destination.geo.continent_code
destination.geo.country_code3
destination.geo.country_iso_code
destination.geo.country_name
destination.geo.ip
destination.geo.latitude
destination.geo.location
destination.geo.longitude
destination.geo.timezone
destination.ip
destination.port
event.created
host
hostname
log.original
log.syslog.priority
observer.name
observer.product
observer.serial_number
observer.type
port
process.name
process.pid
source.ip
source.port
suricata.eve.alert.action
suricata.eve.alert.category
suricata.eve.alert.gid
suricata.eve.alert.metadata.affected_product
suricata.eve.alert.metadata.attack_target
suricata.eve.alert.metadata.created_at
suricata.eve.alert.metadata.deployment
suricata.eve.alert.metadata.former_category
suricata.eve.alert.metadata.performance_impact
suricata.eve.alert.metadata.signature_severity
suricata.eve.alert.metadata.updated_at
suricata.eve.alert.rev
suricata.eve.alert.severity
suricata.eve.alert.signature
suricata.eve.alert.signature_id
suricata.eve.app_proto
suricata.eve.dest_ip
suricata.eve.dest_port
suricata.eve.event_type
suricata.eve.flow.bytes_toclient
suricata.eve.flow.bytes_toserver
suricata.eve.flow.pkts_toclient
suricata.eve.flow.pkts_toserver
suricata.eve.flow.start
suricata.eve.flow_id
suricata.eve.http.hostname
suricata.eve.http.http_method
suricata.eve.http.http_user_agent
suricata.eve.http.length
suricata.eve.http.protocol
suricata.eve.http.redirect
suricata.eve.http.status
suricata.eve.http.url
suricata.eve.in_iface
suricata.eve.proto
suricata.eve.src_ip
suricata.eve.src_port
suricata.eve.timestamp
suricata.eve.tx_id
tags
```

**Comment by a3ilson** [comment] 2020-11-08 14:30
Alright...disregard the prior responses.  I'm testing now but believe the issue is likely the result of [step 4d](https://github.com/3ilson/pfelk/blob/master/install/configuration.md) which has `Enable syslog alerts` checked via OPNsense>>Services>>Intrusion Detection>>Administration.

Those messages are sent via syslog but are not in json format. Essentially, the output logs are being enriched by the json filter (lines 87-126 within 10-apps.conf).  Whereas the syslog alerts are being enriched via a grok pattern and those fields were not defined within the template nor utilized in the dashboard.

I'll let mine run for a bit while I collect some suricata hits and amend as needed.

**Comment by brujoand** [comment] 2020-11-08 14:55
Ah I actually didn't enable syslog alerts. But I made this same install about 2 weeks ago, and did not get these problems for the 8-10 days it was running, so it's very possible that I've made a mistake setting up the config this time. 

And these are the string fields: 
```
@version.keyword
_id
_index
_type
destination.as.organization.name
destination.geo.city_name
destination.geo.continent_code
destination.geo.continent_code.keyword
destination.geo.continent_name
destination.geo.country_code3
destination.geo.country_code3.keyword
destination.geo.country_iso_code
destination.geo.country_name
destination.geo.name
destination.geo.postal_code
destination.geo.postal_code.keyword
destination.geo.region_iso_code
destination.geo.region_name
destination.geo.timezone
destination.geo.timezone.keyword
destination.service
event.created
event.created.keyword
event.outcome
host
host.keyword
hostname
hostname.keyword
http.request.method
log.original
network.protocol
observer.name
observer.name.keyword
observer.product
observer.product.keyword
observer.serial_number
observer.serial_number.keyword
observer.type
observer.type.keyword
process.name
process.pid
source.as.ip
source.as.ip.keyword
source.as.organization.name
source.as.organization.name.keyword
source.geo.as.organization.name
source.geo.city_name
source.geo.continent_code
source.geo.continent_code.keyword
source.geo.country_code3
source.geo.country_code3.keyword
source.geo.country_iso_code
source.geo.country_name
source.geo.name
source.geo.postal_code
source.geo.postal_code.keyword
source.geo.region_iso_code
source.geo.region_name
source.geo.timezone
source.geo.timezone.keyword
source.service
suricata.eve.alert.action
suricata.eve.alert.category
suricata.eve.alert.metadata.affected_product
suricata.eve.alert.metadata.attack_target
suricata.eve.alert.metadata.created_at
suricata.eve.alert.metadata.deployment
suricata.eve.alert.metadata.former_category
suricata.eve.alert.metadata.performance_impact
suricata.eve.alert.metadata.signature_severity
suricata.eve.alert.metadata.update_at
suricata.eve.alert.metadata.updated_at
suricata.eve.alert.metadata.updated_at.keyword
suricata.eve.alert.signature
suricata.eve.app_proto
suricata.eve.dns.query.rrname
suricata.eve.dns.query.rrname.keyword
suricata.eve.dns.query.rrtype
suricata.eve.dns.query.rrtype.keyword
suricata.eve.dns.query.type
suricata.eve.dns.query.type.keyword
suricata.eve.event_type
suricata.eve.flow.start
suricata.eve.flow.start.keyword
suricata.eve.flow_id
suricata.eve.http.hostname
suricata.eve.http.http_content_type
suricata.eve.http.http_content_type.keyword
suricata.eve.http.http_method
suricata.eve.http.http_user_agent
suricata.eve.http.protocol
suricata.eve.http.url
suricata.eve.in_iface
suricata.eve.proto
tags
tags.keyword
url.domain
url.original
user_agent.original
```

**Comment by a3ilson** [comment] 2020-11-08 15:08
Thanks!  There are some differences and possibly additional fields requiring mappings via template. 

Can you provide me with a screenshot of the following:

Kibana>>Management>>Stack Management>>Index Patterns - select `pfelk-suricata*` and provide your field type list.

Example
![Untitled](https://user-images.githubusercontent.com/16884679/98468844-4f170e00-21aa-11eb-8f53-5eec04b9f933.png)

**Comment by a3ilson** [comment] 2020-11-08 15:45
I made a couple of changes within the template which impacts the saved index pattern.  

- [ ] Remove the pfelk-suricata* template 
  - Stack Management>>(Data)Index Management - Index Templates
- [ ] Remove the pfelk-suricata* index pattern
  - Stack Management>>(Kibana)Index Patterns
- [ ] Delete all pfelk-suricata* indices 
  - Stack Management>>(Data)Index Management - Indices
    - You may need to momentarily pause/stop suricata logs until your able to input the updated template 

- [ ] Import the revised template 
  - Dev Tools

```
PUT _template/pfelk-suricata?include_type_name=true
{
  "version": 8,
  "order": 10,
  "index_patterns": [
    "pfelk-suricata*"
  ],
  "settings": {},
  "aliases": {},
  "mappings": {
    "mappings": {
      "_routing": {
        "required": false
      },
      "numeric_detection": false,
      "_source": {
        "excludes": [],
        "includes": [],
        "enabled": true
      },
      "dynamic": true,
      "dynamic_templates": [
        {
          "message_field": {
            "path_match": "message",
            "mapping": {
              "norms": false,
              "type": "text"
            },
            "match_mapping_type": "string"
          }
        },
        {
          "string_fields": {
            "mapping": {
              "norms": false,
              "type": "text",
              "fields": {
                "keyword": {
                  "ignore_above": 1024,
                  "type": "keyword"
                }
              }
            },
            "match_mapping_type": "string",
            "match": "*"
          }
        }
      ],
      "date_detection": false,
      "properties": {
        "user_agent.original": {
          "path": "suricata.eve.http.http_user_agent",
          "type": "alias"
        },
        "destination": {
          "type": "object",
          "properties": {
            "port": {
              "coerce": true,
              "index": true,
              "ignore_malformed": false,
              "store": false,
              "type": "integer",
              "doc_values": true
            },
            "bytes": {
              "path": "suricata.eve.flow.bytes_toclient",
              "type": "alias"
            },
            "service": {
              "type": "keyword"
            },
            "ip": {
              "index": true,
              "store": false,
              "type": "ip",
              "doc_values": true
            },
            "packets": {
              "path": "suricata.eve.flow.bytes_toclient",
              "type": "alias"
            }
          }
        },
        "http": {
          "type": "object",
          "properties": {
            "request": {
              "type": "object",
              "properties": {
                "method": {
                  "path": "suricata.eve.http.http_method",
                  "type": "alias"
                }
              }
            },
            "response": {
              "type": "object",
              "properties": {
                "body": {
                  "type": "object",
                  "properties": {
                    "bytes": {
                      "path": "suricata.eve.http.length",
                      "type": "alias"
                    }
                  }
                }
              }
            }
          }
        },
        "suricata": {
          "type": "object",
          "properties": {
            "eve": {
              "type": "object",
              "properties": {
                "tx_id": {
                  "type": "long"
                },
                "app_proto": {
                  "type": "keyword"
                },
                "in_iface": {
                  "type": "keyword"
                },
                "src_ip": {
                  "index": true,
                  "store": false,
                  "type": "ip",
                  "doc_values": true
                },
                "src_port": {
                  "coerce": true,
                  "index": true,
                  "ignore_malformed": false,
                  "store": false,
                  "type": "integer",
                  "doc_values": true
                },
                "event_type": {
                  "type": "keyword"
                },
                "alert": {
                  "type": "object",
                  "properties": {
                    "severity": {
                      "type": "long"
                    },
                    "metadata": {
                      "type": "object",
                      "properties": {
                        "performance_impact": {
                          "type": "keyword"
                        },
                        "affected_product": {
                          "type": "keyword"
                        },
                        "attack_target": {
                          "type": "keyword"
                        },
                        "former_category": {
                          "type": "keyword"
                        },
                        "update_at": {
                          "format": "strict_date_optional_time||epoch_millis||YYYY_MM_DD",
                          "index": true,
                          "ignore_malformed": false,
                          "store": false,
                          "type": "date",
                          "doc_values": true
                        },
                        "created_at": {
                          "format": "strict_date_optional_time||epoch_millis||YYYY_MM_DD",
                          "index": true,
                          "ignore_malformed": false,
                          "store": false,
                          "type": "date",
                          "doc_values": true
                        },
                        "signature_severity": {
                          "type": "keyword"
                        },
                        "deployment": {
                          "type": "keyword"
                        }
                      }
                    },
                    "rev": {
                      "type": "long"
                    },
                    "signature_id": {
                      "type": "long"
                    },
                    "gid": {
                      "type": "long"
                    },
                    "signature": {
                      "type": "keyword"
                    },
                    "action": {
                      "eager_global_ordinals": false,
                      "norms": false,
                      "index": true,
                      "store": false,
                      "type": "keyword",
                      "split_queries_on_whitespace": false,
                      "index_options": "docs",
                      "doc_values": true
                    },
                    "category": {
                      "type": "keyword"
                    }
                  }
                },
                "flow_id": {
                  "type": "keyword"
                },
                "dest_ip": {
                  "type": "ip"
                },
                "proto": {
                  "type": "keyword"
                },
                "http": {
                  "type": "object",
                  "properties": {
                    "hostname": {
                      "eager_global_ordinals": false,
                      "norms": false,
                      "index": true,
                      "store": false,
                      "type": "keyword",
                      "split_queries_on_whitespace": false,
                      "index_options": "docs",
                      "doc_values": true
                    },
                    "protocol": {
                      "type": "keyword"
                    },
                    "http_method": {
                      "eager_global_ordinals": false,
                      "norms": false,
                      "index": true,
                      "store": false,
                      "type": "keyword",
                      "split_queries_on_whitespace": false,
                      "index_options": "docs",
                      "doc_values": true
                    },
                    "length": {
                      "type": "long"
                    },
                    "url": {
                      "eager_global_ordinals": false,
                      "norms": false,
                      "index": true,
                      "store": false,
                      "type": "keyword",
                      "split_queries_on_whitespace": false,
                      "index_options": "docs",
                      "doc_values": true
                    },
                    "http_user_agent": {
                      "eager_global_ordinals": false,
                      "index_phrases": false,
                      "fielddata": false,
                      "norms": false,
                      "index": true,
                      "store": false,
                      "type": "text",
                      "index_options": "docs"
                    }
                  }
                },
                "dest_port": {
                  "coerce": true,
                  "index": true,
                  "ignore_malformed": false,
                  "store": false,
                  "type": "integer",
                  "doc_values": true
                },
                "flow": {
                  "type": "object",
                  "properties": {
                    "pkts_toserver": {
                      "type": "integer"
                    },
                    "flow_id": {
                      "type": "keyword"
                    },
                    "start": {
                      "index": true,
                      "ignore_malformed": false,
                      "store": false,
                      "type": "date",
                      "doc_values": true
                    },
                    "bytes_toclient": {
                      "type": "long"
                    },
                    "bytes_toserver": {
                      "type": "long"
                    },
                    "pkts_toclient": {
                      "type": "integer"
                    }
                  }
                },
                "timestamp": {
                  "type": "date"
                }
              }
            }
          }
        },
        "source": {
          "type": "object",
          "properties": {
            "port": {
              "type": "integer"
            },
            "bytes": {
              "path": "suricata.eve.flow.bytes_toserver",
              "type": "alias"
            },
            "service": {
              "type": "keyword"
            },
            "ip": {
              "type": "ip"
            },
            "packets": {
              "path": "suricata.eve.flow.pkts_toserver",
              "type": "alias"
            }
          }
        },
        "event": {
          "type": "object",
          "properties": {
            "severity": {
              "path": "suricata.eve.alert.severity",
              "type": "alias"
            },
            "outcome": {
              "path": "suricata.eve.alert.action",
              "type": "alias"
            }
          }
        },
        "url": {
          "type": "object",
          "properties": {
            "original": {
              "path": "suricata.eve.http.url",
              "type": "alias"
            },
            "domain": {
              "path": "suricata.eve.http.hostname",
              "type": "alias"
            }
          }
        },
        "network": {
          "type": "object",
          "properties": {
            "protocol": {
              "path": "suricata.eve.app_proto",
              "type": "alias"
            }
          }
        }
      }
    }
  }
}
```

Let it run, collect and let me know if the issue persists.

**Comment by brujoand** [comment] 2020-11-10 07:42
Thanks! I did follow your steps and It's been running since yesterday. I'm not seeing any issues with shards today, but I instantly got a problem when opening the suricata dashboard. Basically telling me `Could not locate that index-pattern (id: suricata), click here to re-create it`. So I clicked and re-added it using @timestamp as the date field. But still only the Flow graph is visible. I'm not seeing anything interesting in the logs, so I'm not quite sure what's wrong here?

**Comment by a3ilson** [comment] 2020-11-10 15:12
@brujoand - Depending on your setup collecting suricata logs may take time to acquire. 

Please check with suricata to validate events being collected and logs being sent:

![Capture](https://user-images.githubusercontent.com/16884679/98691806-6be34b00-233c-11eb-8719-9145257a8fbc.PNG)

Next, how are you sending your suricata logs and can you confirm that they are being sent:

![Capture](https://user-images.githubusercontent.com/16884679/98692173-d2686900-233c-11eb-90b9-fb5e241273f8.PNG)

Lastly, when you navigate to Kibana>>Discover are the logs matching those within OPNsense (e.g. Services>>Intrusion Detection>>Log File)
![Capture](https://user-images.githubusercontent.com/16884679/98692480-2d01c500-233d-11eb-9698-d8a645cffc50.PNG)

**Comment by brujoand** [comment] 2020-11-10 15:21
![image](https://user-images.githubusercontent.com/124421/98693089-22acee80-2370-11eb-8da2-f1563f32ce5d.jpeg)

Yeah, OPNsense is still configured to forward the logs and  it looks like they are getting through ref the screenshot above. And in the dashboard the "flow" tile is working, it's just all the other tiles that are displaying the error _Could not locate that index-pattern (id: suricata), click here to re-create it_

I guess I'll maybe a typo could have snuck in somewhere. I'll look for that next.

**Comment by a3ilson** [comment] 2020-11-10 15:54
Awe....when you created the index pattern you likely forgot to provide the custom index pattern ID.  This is incorporate in the Dashboard file and not sure why it didn't work in your case. 

Try removing the pfelk-suricata* index pattern and recreating with the custom index pattern ID or remove all suricata saved objects and try importing again.

![Capture](https://user-images.githubusercontent.com/16884679/98697393-e1eab080-2342-11eb-846f-f60589f6a496.PNG)

**Comment by brujoand** [comment] 2020-11-10 16:12
Sweet, that worked! Thanks 👍

**Comment by a3ilson** [comment] 2020-11-10 16:16
Excellent! Issue resolved and closing.

**Closed as completed by a3ilson** 2020-11-10 16:16 UTC
Labels: bug, wip, waiting-author-response
