### ISSUE TITLE
install script (not debian friendly)

### ISSUE THREAD

**Issue by repomanz** [pfelk/pfelk#94] opened 2020-04-18 14:58 UTC
**Describe the bug**
Install script is not debian 9 or 10 friendly.  Script appears to be adding ubuntu repos (ie ppa)

**To Reproduce**
run  install script on debian 9 or 10

**Comment by a3ilson** [comment] 2020-04-18 15:44
@repomanz - thanks!  I'll correct and troubleshoot this later today.

**Comment by a3ilson** [comment] 2020-04-19 04:50
@repomanz - I updated the script...give it another attempt and let me know if it works with Debian 9 and/or 10.

**Comment by repomanz** [comment] 2020-04-19 16:30
I'll need to spin up a fresh VM. Will report back in a couple days

**Comment by repomanz** [comment] 2020-04-19 18:06
Fresh install of debian 10:   You may also need to either include pre-req that sudo is required to be configured or handle it as part of your script.  Sudo does not come installed with debian by default.

packages not found:
xxxxxx@vmdeblog:~$ sudo ./ez-pfelk-installer.sh
pfELK: Installing Inital Dependencies & Added Respositories
Selecting previously unselected package apt-transport-https.
(Reading database ... 27970 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.8.2_all.deb ...
Unpacking apt-transport-https (1.8.2) ...
Setting up apt-transport-https (1.8.2) ...
sudo: add-apt-repository: command not found
deb https://artifacts.elastic.co/packages/7.x/apt stable main
**E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
pfELK: apt-get failed**

**Comment by repomanz** [comment] 2020-04-19 20:30
script input:

1. elastic needs package: gnupg2

2. regarding java - not sure if you intend on debian installing openjdk.
xxxxx@vmdeblog:~$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)

3. script doesn't handle populating geoip.conf like like it does in ubuntu

**Comment by a3ilson** [comment] 2020-04-19 21:18
@repomanz - I'll fire up a Debian Server this week and revise the script.  Thanks the feedback!

**Comment by repomanz** [comment] 2020-04-19 21:20
sadly; there is something up with Debian 10.  I went through your script, updated based on above and am in the same boat as the other ticket.

**Comment by a3ilson** [comment] 2020-04-19 21:29
@repomanz - I am confident everything is working but am curious as to what the issue is...have you dabbled with the UFW?  It's odd because, you received the logs when running tcpdump...I'll troubleshoot this week and see if I can isolate the culprit.

**Comment by repomanz** [comment] 2020-04-19 21:37
ufw:  the os firewall that you can enable in ubuntu, debian and arch?  I've heard of it but never needed to to use it for internal servers/clients.   what you thinking?

**Comment by a3ilson** [comment] 2020-04-20 00:53
Disregard...it doesn't' appear to be enabled by default - doubtful it is the culprit.  It's on my list for this weeks troubleshooting.

**Comment by revere521** [comment] 2020-04-20 14:08
with Debian, you may need to install 'software-properties-common' to add repositories with the 'add-apt-repository' command

**Comment by repomanz** [comment] 2020-04-20 14:39
correct - previously though, it added a ubuntu path :)

**Comment by revere521** [comment] 2020-04-21 12:15
ahh ok, so is this fixed now - the ez script works just fine on debian?

**Comment by repomanz** [comment] 2020-04-21 14:00
No - i'd suggest installing fresh debian 10 install to work out the debian kinks.  Still nothing coming into logstash.

**Comment by revere521** [comment] 2020-04-22 18:32
Ok, i've been playing with this a bit on a Debian 10 VM, and the following are dependencies for the add-apt-repository to succeed (including the elastic 7.x one added with the echo command) and their related pgp keys: 

`software-properties-common dirmngr apt-transport-https lsb-release ca-certificates`

The problem I havn't fixed yet, is that Debian does not like the InRelease file in the maxmind ppa.  It may need to be installed from a deb file, even though the geoipupdate is listed in the Buster repository.....

**Comment by revere521** [comment] 2020-04-22 20:16
This script is super dirty with the deb file, but it works on Debian: 
```

#!/bin/sh
# Use this script to install OS dependencies, downloading and compile pfELK dependencies

# This script will
# * use apt-get/yum to install OS dependancies
# * download known working versions of pfELK dependencies
# * configure pfELK <-- In Work... Configuration Script
# * install Elasticstack
# * install Java 11 LTS
# * install Maxmind (GeoIP) <-- In Work... Configuration Script
# * install apt-trasnport-https (ATH)

# Check the existance of sudo
command -v sudo >/dev/null 2>&1 || { echo >&2 "pfELK: sudo is required to be installed"; exit 1; }

# Installing pfELK dependencies
echo "pfELK: Installing Inital Dependencies & Added Respositories"
if [ -f "/etc/redhat-release" ] || [ -f "/etc/system-release" ]; then
  sudo yum -y install wget apt-transport-https; sudo yum add-apt-repository ppa:maxmind/ppa; sudo echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list; sudo wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  if [ $? -ne 0 ]; then
    echo "pfELK: yum failed"
    exit 1
  fi
fi

if [ -f "/etc/debian_version" ]; then
  sudo apt-get -qq install wget apt-transport-https software-properties-common dirmngr lsb-release ca-certificates; sudo echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list; sudo wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  if [ $? -ne 0 ]; then
    echo "pfELK: apt-get failed"
    exit 1
  fi
fi

#if [ "$UNAME" = "FreeBSD" ]; then
#  sudo pkg_add -Fr wget apt-transport-https; sudo add-apt-repository ppa:maxmind/ppa; sudo echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list; sudo wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
#  MAKE=gmake
#fi

# Update Required Respositories
echo "pfELK: Updating Respositories"
if [ -f "/etc/redhat-release" ] || [ -f "/etc/system-release" ]; then
  sudo yum -y update
  if [ $? -ne 0 ]; then
    echo "pfELK: yum failed"
    exit 1
  fi
fi

if [ -f "/etc/debian_version" ]; then
  sudo apt-get -qq update
  if [ $? -ne 0 ]; then
    echo "pfELK: apt-get failed"
    exit 1
  fi
  fi
fi

#if [ "$UNAME" = "FreeBSD" ]; then
#  sudo pkg_add -Fr update
#  MAKE=gmake
#fi

# Install Required Respositories
echo "pfELK: Installing Required Respositories"
if [ -f "/etc/redhat-release" ] || [ -f "/etc/system-release" ]; then
  sudo yum -y install openjdk-11-jre; sudo apt-get -qq install geoipupdate; sudo apt-get -qq install elasticsearch; sudo apt-get -qq install kibana; sudo apt-get -qq install logstash
  if [ $? -ne 0 ]; then
    echo "pfELK: yum failed"
    exit 1
  fi
fi

if [ -f "/etc/debian_version" ]; then
  sudo apt-get -qq install openjdk-11-jre; sudo apt-get -qq install elasticsearch; sudo apt-get -qq install kibana; sudo apt-get -qq install logstash; cd $HOME; wget https://github.com/maxmind/geoipupdate/releases/download/v4.3.0/geoipupdate_4.3.0_linux_amd64.deb; sudo dpkg -i ./geoipupdate_4.3.0_linux_amd64.deb
  if [ $? -ne 0 ]; then
    echo "pfELK: apt-get failed"
    exit 1
  fi
fi

#if [ "$UNAME" = "FreeBSD" ]; then
#  sudo pkg_add -Fr install openjdk-11-jre; sudo apt-get -qq install geoipupdate; sudo apt-get -qq install elasticsearch; sudo apt-get -qq install kibana; sudo apt-get -qq install logstash
#  MAKE=gmake
#fi

# System Configuration
echo "pfELK: System Optimization"
sudo swapoff -a

# Download Configuration & Pattern
  echo "pfELK: Retrieving Confguration Files"
  sudo mkdir /etc/logstash/conf.d/patterns
  sudo mkdir /etc/logstash/conf.d/template
  cd /etc/logstash/conf.d
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/01-inputs.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/05-firewall.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/10-others.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/20-suricata.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/25-snort.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/30-geoip.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/40-dns.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/45-cleanup.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/50-outputs.conf
  cd /etc/logstash/conf.d/patterns
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/patterns/pfelk.grok
  cd /etc/logstash/conf.d/template
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/template/pf-geoip-template.json

# Add Configuration Script Here
# Install/Troubleshoot Success Message
  sudo mkdir /etc/pfelk
  cd /etc/pfelk
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/readme.txt
  cat readme.txt

exit 0

```

**Comment by a3ilson** [comment] 2020-04-22 20:27
@revere521 - I was just getting ready to dabble with the script....awaiting for my Debian snapshot to load.  Well you beat me to it - thanks!  Feel free to update and push the file.

**Comment by a3ilson** [comment] 2020-04-22 20:30
I'll test it out in a bit and see if I isolate the issue with Debian (v10.3) receiving logs - #92

**Comment by repomanz** [comment] 2020-04-22 20:59
Hey guys, for debian 10 default installs the gnupg2 package is required for elasticsearch.   I don't see that currently in the script.  I'll try whatever script you guys have this weekend on a fresh debian 10 install

**Comment by revere521** [comment] 2020-04-22 22:13
I would push the file, but i think it will need to be reviewed and cleaned up.  It looks like it might break ubuntu installs.   I was shooting for getting it to work just to isolate the issue. 

I did just manually install gnupg2, not sure if it was needed; but my instance on Debian 10 is running fine after configured (pfsense 2.4.5, snort) and ingesting data just fine in logstash

**Comment by repomanz** [comment] 2020-04-22 22:17
Interesting; i did a fresh install, tried both manual and scripted debian installs and even though tcp dump was showing logs coming into the host, they woudn't get consumed.  By chance are you on metal or vm install of debian?  I'm on kvm linux debian guest vm.

Repeated process on kvm linux ubuntu 18.04lts vm build (both scripted and manual) and it was a one shot.

**Comment by revere521** [comment] 2020-04-22 22:19
its a Virtualbox Debian 10 VM on a Windows desktop host.  At first it didn't work, but i had accidentally uncommented out the wrong line in 01-inputs.conf

**Comment by revere521** [comment] 2020-04-22 22:23
@a3ilson the script could be used if we found a different way to identify debian v ubuntu.  
since -f "/etc/debian_version" won't distinguish between the two.  

I'm looking for a simple way to do it that

**Comment by repomanz** [comment] 2020-04-22 22:46
@revere521  this works in both debian and ubuntu:  hostnamectl | grep Operating

xxx@vmubntlog:~$ hostnamectl | grep Operating
  Operating System: Ubuntu 18.04.4 LTS

xxx@vmdebpihole:~$ hostnamectl | grep Operating
  Operating System: Debian GNU/Linux 10 (buster)

**Comment by revere521** [comment] 2020-04-22 23:09
excellent, it looks like i can replace the line
`if [ -f "/etc/debian_version" ]; then`

With:
`if hostnamectl | grep debian > /dev/null; then`
and
`if hostnamectl | grep ubuntu > /dev/null; then`

I will finish this up and then start over with fresh Ubuntu and Debian VMs and test on each to make sure it doesn't make smoke.

**Comment by revere521** [comment] 2020-04-22 23:13
Edit: Confirmed this works on Debian 10.3 just fine.  building a fresh Ubuntu 18.04 VM now to test. 


This is what I have to test - for peer review:

```

#!/bin/sh
# Use this script to install OS dependencies, downloading and compile pfELK dependencies

# This script will
# * use apt-get/yum to install OS dependancies
# * download known working versions of pfELK dependencies
# * configure pfELK <-- In Work... Configuration Script
# * install Elasticstack
# * install Java 11 LTS
# * install Maxmind (GeoIP) <-- In Work... Configuration Script
# * install apt-trasnport-https (ATH)

# Check the existance of sudo
command -v sudo >/dev/null 2>&1 || { echo >&2 "pfELK: sudo is required to be installed"; exit 1; }

# Installing pfELK dependencies
echo "pfELK: Installing Inital Dependencies & Added Respositories"

#Redhat
if [ -f "/etc/redhat-release" ] || [ -f "/etc/system-release" ]; then
  sudo yum -y install wget apt-transport-https; sudo yum add-apt-repository ppa:maxmind/ppa; sudo echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list; sudo wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  if [ $? -ne 0 ]; then
    echo "pfELK: yum failed"
    exit 1
  fi
fi

#Debian
if hostnamectl | grep 'Operating System: Debian*' > /dev/null; then
  sudo apt-get -qq install wget apt-transport-https gnupg2 software-properties-common dirmngr lsb-release ca-certificates; sudo echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list; sudo wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  if [ $? -ne 0 ]; then
    echo "pfELK: apt-get failed"
    exit 1
  fi
fi

#Ubuntu
if hostnamectl | grep 'Operating System: Ubuntu*' > /dev/null; then
  sudo apt-get -qq install wget apt-transport-https; sudo add-apt-repository ppa:maxmind/ppa; sudo echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list; sudo wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  if [ $? -ne 0 ]; then
    echo "pfELK: apt-get failed"
    exit 1
  fi
fi

#FreeBSD (forthcoming)
#if [ "$UNAME" = "FreeBSD" ]; then
#  sudo pkg_add -Fr wget apt-transport-https; sudo add-apt-repository ppa:maxmind/ppa; sudo echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list; sudo wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
#  MAKE=gmake
#fi


# Update Required Respositories
echo "pfELK: Updating Respositories"
#Redhat
if [ -f "/etc/redhat-release" ] || [ -f "/etc/system-release" ]; then
  sudo yum -y update
  if [ $? -ne 0 ]; then
    echo "pfELK: yum failed"
    exit 1
  fi
fi

#Debian
if hostnamectl | grep 'Operating System: Debian*' > /dev/null; then
  sudo apt-get -qq update
  if [ $? -ne 0 ]; then
    echo "pfELK: apt-get failed"
    exit 1
  fi
fi

#Ubuntu
if hostnamectl | grep 'Operating System: Ubuntu*' > /dev/null; then
  sudo apt-get -qq update 
  if [ $? -ne 0 ]; then
    echo "pfELK: apt-get failed"
    exit 1
  fi
fi

#FreeBSD (forthcoming)
#if [ "$UNAME" = "FreeBSD" ]; then
#  sudo pkg_add -Fr update
#  MAKE=gmake
#fi

# Install Required Respositories
echo "pfELK: Installing Required Respositories - This may take some time, Please be patient"

#Redhat
if [ -f "/etc/redhat-release" ] || [ -f "/etc/system-release" ]; then
  sudo yum -y install openjdk-11-jre; sudo apt-get -qq install geoipupdate; sudo apt-get -qq install elasticsearch; sudo apt-get -qq install kibana; sudo apt-get -qq install logstash
  if [ $? -ne 0 ]; then
    echo "pfELK: yum failed"
    exit 1
  fi
fi

#Debian
if hostnamectl | grep 'Operating System: Debian*' > /dev/null; then
  sudo apt-get -qq install openjdk-11-jre; sudo apt-get -qq install elasticsearch; sudo apt-get -qq install kibana; sudo apt-get -qq install logstash; cd $HOME; wget https://github.com/maxmind/geoipupdate/releases/download/v4.3.0/geoipupdate_4.3.0_linux_amd64.deb; sudo dpkg -i ./geoipupdate_4.3.0_linux_amd64.deb
  if [ $? -ne 0 ]; then
    echo "pfELK: apt-get failed"
    exit 1
  fi
fi

#Ubuntu
if hostnamectl | grep 'Operating System: Ubuntu*' > /dev/null; then
  sudo apt -qq install openjdk-11-jre; sudo apt-get -qq install geoipupdate; sudo apt-get -qq install elasticsearch; sudo apt-get -qq install kibana; sudo apt-get -qq install logstash
  if [ $? -ne 0 ]; then
    echo "pfELK: apt-get failed"
    exit 1
  fi
fi


#FreeBSD (forthcoming)
#if [ "$UNAME" = "FreeBSD" ]; then
#  sudo pkg_add -Fr install openjdk-11-jre; sudo apt-get -qq install geoipupdate; sudo apt-get -qq install elasticsearch; sudo apt-get -qq install kibana; sudo apt-get -qq install logstash
#  MAKE=gmake
#fi

# System Configuration
echo "pfELK: System Optimization"
sudo swapoff -a

# Download Configuration & Pattern
  echo "pfELK: Retrieving Confguration Files"
  sudo mkdir /etc/logstash/conf.d/patterns
  sudo mkdir /etc/logstash/conf.d/template
  cd /etc/logstash/conf.d
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/01-inputs.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/05-firewall.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/10-others.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/20-suricata.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/25-snort.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/30-geoip.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/40-dns.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/45-cleanup.conf
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/50-outputs.conf
  cd /etc/logstash/conf.d/patterns
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/patterns/pfelk.grok
  cd /etc/logstash/conf.d/template
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/template/pf-geoip-template.json

##
# Add Configuration Script Here
##

# Install/Troubleshoot Success Message
  sudo mkdir /etc/pfelk
  cd /etc/pfelk
  sudo wget https://raw.githubusercontent.com/3ilson/pfelk/master/readme.txt
  cat readme.txt

exit 0
```

**Comment by a3ilson** [comment] 2020-04-23 02:24
@revere521 - Thanks!  I'll be testing this tomorrow but feel free to update within the repo.  You can also add the 35-rules-desc.conf file.

**Comment by revere521** [comment] 2020-04-23 03:06
My DSL is slow so its still downloading some stuff - but it appears to be installing just fine in Ubuntu too.  I updated the script in the repo. 

I will confirm the successful install in the AM if necessary

**Comment by revere521** [comment] 2020-04-23 14:28
Confirmed Ubuntu works as well

Note that logstash fails spectacularly with java errors if you forget to run geoipupdate, and then you pull your hair out for several hours before you realize you just needed a little more coffee

**Comment by a3ilson** [comment] 2020-04-23 15:38
@revere512 - Thanks for your assistance and help with this!  I’ll look into
updating the geoip file similarly to that of the 35-rule-desc file.

Added a logic function prior to applying geoip filtering thus mitigating
errors.  I’ll add a tag to indicate geoip is not configured.

**Comment by a3ilson** [comment] 2020-04-24 23:32
Script and manual method both tested on fresh vanilla install of Debian 10.3.  No issues....closing this issue.

**Closed as completed by a3ilson** 2020-04-24 23:32 UTC
Labels: bug, setup/config issue
